packages:
  - 'app'
  - 'components/**'
  - 'lib/**'

allowBuilds:
  msw: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@parcel/watcher'
  - 'sharp'
  - 'esbuild'
  - 'unrs-resolver'
  - 'msw'
