'use client'

import { ArrowRight, Filter, Search } from 'lucide-react'
import { ProductCard } from '@/components/cards/product-card'
import { PageContainer, PageHeader } from '@/components/pages/shared/page-header'
import type { Product, SetView } from '@/lib/types'

const categories = ['Todos', 'Alimentos', 'Accesorios', 'Cuidado']
export default function ShopPage({ products, search, setSearch, category, setCategory, addToCart, setView }: { products: Product[]; search: string; setSearch: (value: string) => void; category: string; setCategory: (value: string) => void; addToCart: (product: Product) => void; setView: SetView }) {
  return <PageContainer><PageHeader eyebrow="Akimax pet shop" title="Todo lo que mueve sus patitas" description="Productos seleccionados para una vida más sana, cómoda y feliz." action={<button onClick={() => setView('servicios')} className="flex items-center gap-2 text-sm font-bold text-[#0d5c5b]">Ver servicios <ArrowRight className="size-4" /></button>} /><div className="mt-8 flex flex-col gap-6 lg:flex-row"><ShopFilters category={category} setCategory={setCategory} /><div className="min-w-0 flex-1"><div className="relative mb-6"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[#8ca59c]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar producto..." className="w-full rounded-2xl border-0 bg-white py-4 pl-11 pr-4 text-sm outline-none ring-1 ring-[#e1ebe6] focus:ring-2 focus:ring-[#9ec6b0]" /></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <ProductCard key={product.id} product={product} onAdd={() => addToCart(product)} />)}</div>{products.length === 0 && <p className="rounded-3xl bg-white p-12 text-center text-sm text-[#78918a] ring-1 ring-[#e1ebe6]">No encontramos productos con esos filtros.</p>}</div></div></PageContainer>
}
function ShopFilters({ category, setCategory }: { category: string; setCategory: (value: string) => void }) { return <aside className="h-fit shrink-0 rounded-3xl bg-white p-5 ring-1 ring-[#e1ebe6] lg:w-60"><div className="flex items-center justify-between"><b className="text-[#173b3b]">Filtrar por</b><Filter className="size-4 text-[#829990]" /></div><div className="mt-5 flex gap-2 overflow-x-auto lg:flex-col">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-left text-sm ${category === item ? 'bg-[#e7f1eb] font-bold text-[#0d5c5b]' : 'text-[#78918a] hover:bg-[#f4f8f5]'}`}>{item}</button>)}</div><div className="mt-8 hidden border-t border-[#e7eee9] pt-5 text-sm text-[#66817a] lg:block"><p className="text-xs font-bold uppercase tracking-wide text-[#829990]">Stock disponible</p><p className="mt-4">En existencia</p><p className="mt-3">Últimas unidades</p></div></aside> }
