-- ============================================================
-- akimax pet — Migración 0017: Seed razas de perros y gatos
-- ============================================================

-- RAZAS DE PERRO (species_id 1)
insert into public.breeds (species_id, name, slug) values
  (1, 'Labrador Retriever', 'labrador'),
  (1, 'Golden Retriever', 'golden'),
  (1, 'Pastor Alemán', 'pastor-aleman'),
  (1, 'Bulldog Francés', 'bulldog-frances'),
  (1, 'Bulldog Inglés', 'bulldog-ingles'),
  (1, 'Poodle (Caniche)', 'poodle'),
  (1, 'Beagle', 'beagle'),
  (1, 'Rottweiler', 'rottweiler'),
  (1, 'Yorkshire Terrier', 'yorkshire'),
  (1, 'Dachshund (Salchicha)', 'dachshund'),
  (1, 'Boxer', 'boxer'),
  (1, 'Siberian Husky', 'husky'),
  (1, 'Chihuahua', 'chihuahua'),
  (1, 'Shih Tzu', 'shih-tzu'),
  (1, 'Pomerania', 'pomerania'),
  (1, 'Dálmata', 'dalmata'),
  (1, 'Pug (Carlino)', 'pug'),
  (1, 'Cocker Spaniel', 'cocker'),
  (1, 'Border Collie', 'border-collie'),
  (1, 'Maltés', 'maltes'),
  (1, 'Pitbull Terrier', 'pitbull'),
  (1, 'Doberman', 'doberman'),
  (1, 'Gran Danés', 'gran-danes'),
  (1, 'San Bernardo', 'san-bernardo'),
  (1, 'Mastín Napolitano', 'mastin'),
  (1, 'Samoyedo', 'samoyedo'),
  (1, 'Corgi Galés', 'corgi'),
  (1, 'Schnauzer Miniatura', 'schnauzer'),
  (1, 'West Highland Terrier', 'westie'),
  (1, 'Jack Russell Terrier', 'jack-russell'),
  (1, 'Bichón Frisé', 'bichon'),
  (1, 'Boston Terrier', 'boston'),
  (1, 'Chow Chow', 'chow-chow'),
  (1, 'Akita Inu', 'akita'),
  (1, 'Shiba Inu', 'shiba'),
  (1, 'Shar Pei', 'shar-pei'),
  (1, 'Basenji', 'basenji'),
  (1, 'Bloodhound', 'bloodhound'),
  (1, 'Borzoi', 'borzoi'),
  (1, 'Whippet', 'whippet'),
  (1, 'Galgo Español', 'galgo-espanol'),
  (1, 'Irish Setter', 'irish-setter'),
  (1, 'Weimaraner', 'weimaraner'),
  (1, 'Vizsla', 'vizsla'),
  (1, 'Papillón', 'papillon'),
  (1, 'Pekinés', 'pekines'),
  (1, 'Bichón Habanero', 'habanero'),
  (1, 'Fox Terrier', 'fox-terrier'),
  (1, 'Airedale Terrier', 'airedale'),
  (1, 'Perro de Agua Español', 'agua-espanol'),
  (1, 'Podencos', 'podenco'),
  (1, 'Presa Canario', 'presa-canario'),
  (1, 'Pastor Canario', 'pastor-canario'),
  (1, 'Perro de Montaña de los Pirineos', 'pirineos'),
  (1, 'Komondor', 'komondor'),
  (1, 'Puli', 'puli'),
  (1, 'Alaskan Malamute', 'alaskan'),
  (1, 'Australian Cattle Dog', 'australian-cattle'),
  (1, 'Australian Shepherd', 'australian-shepherd'),
  (1, 'Belgian Malinois', 'malinois'),
  (1, 'Collie (Rough)', 'rough-collie'),
  (1, 'Shetland Sheepdog', 'sheltie'),
  (1, 'Old English Sheepdog', 'old-english'),
  (1, 'Tibetan Mastiff', 'tibetan'),
  (1, 'Leonberger', 'leonberger'),
  (1, 'Newfoundland', 'newfoundland'),
  (1, 'Mestizo/Criollo', 'mestizo')
on conflict (species_id, name) do nothing;

-- RAZAS DE GATO (species_id 2)
insert into public.breeds (species_id, name, slug) values
  (2, 'Siamés', 'siames'),
  (2, 'Persa', 'persa'),
  (2, 'Maine Coon', 'maine-coon'),
  (2, 'Bengalí', 'bengali'),
  (2, 'Sphynx', 'sphynx'),
  (2, 'British Shorthair', 'british'),
  (2, 'Gato Común Europeo', 'europeo'),
  (2, 'Ragdoll', 'ragdoll'),
  (2, 'Exótico', 'exotico'),
  (2, 'Azul Ruso', 'azul-ruso'),
  (2, 'Siberiano', 'siberiano'),
  (2, 'Munchkin', 'munchkin'),
  (2, 'Oriental', 'oriental'),
  (2, 'Abisinio', 'abisinio'),
  (2, 'Birmano', 'birmano'),
  (2, 'Devon Rex', 'devon-rex'),
  (2, 'Cornish Rex', 'cornish'),
  (2, 'Bombay', 'bombay'),
  (2, 'Himalayo', 'himalayo'),
  (2, 'Scottish Fold', 'scottish'),
  (2, 'Mestizo/Criollo', 'mestizo')
on conflict (species_id, name) do nothing;