'use client'

import { ChevronRight, HeartPulse, Plus } from 'lucide-react'
import { pets } from '@/lib/mock-data'
import type { Toast } from '@/lib/types'
import { PageContainer, PageHeader } from '@/components/pages/shared/page-header'

export default function PatientsPage({ showToast }: { showToast: Toast }) {
  return <PageContainer><PageHeader eyebrow="Mi familia" title="Mis mascotas" description="Sus historias, vacunas y próximos cuidados en un solo lugar." action={<button onClick={() => showToast('Formulario para registrar mascota abierto')} className="inline-flex items-center gap-2 rounded-xl bg-[#0d5c5b] px-4 py-3 text-sm font-bold text-white"><Plus className="size-4" /> Agregar mascota</button>} /><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_1.2fr]"><PetList /><PetHistory /></div></PageContainer>
}
function PetList() { return <div className="flex flex-col gap-4">{pets.map((pet, index) => <button key={pet.name} className={`rounded-3xl bg-white p-5 text-left ring-1 transition-all ${index === 0 ? 'ring-[#9fc9b5] shadow-md' : 'ring-[#e1ebe6]'}`}><div className="flex items-center gap-4"><span className={`flex size-14 items-center justify-center rounded-2xl ${pet.color} font-serif font-bold text-[#477267]`}>{pet.initials}</span><span><b className="font-serif text-xl text-[#173b3b]">{pet.name}</b><span className="mt-1 block text-sm text-[#829990]">{pet.species}</span></span><ChevronRight className="ml-auto size-5 text-[#a0b5ac]" /></div><p className="mt-5 border-t border-[#edf1ee] pt-4 text-xs text-[#829990]">{pet.last}</p></button>)}</div> }
function PetHistory() { return <section className="rounded-3xl bg-white p-6 ring-1 ring-[#e1ebe6] md:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#d37c52]">Historia clínica</p><h2 className="mt-2 font-serif text-3xl font-bold text-[#173b3b]">Luna</h2><p className="mt-1 text-sm text-[#829990]">Golden Retriever · 4 años · 18.5 kg</p></div><span className="flex size-12 items-center justify-center rounded-2xl bg-[#e7f1eb] text-[#0d5c5b]"><HeartPulse className="size-6" /></span></div><div className="mt-8 flex flex-col gap-7 border-l border-[#dce7e2] pl-6"><div><p className="text-xs font-bold text-[#d37c52]">12 Jun 2024</p><h3 className="mt-1 font-serif text-xl font-bold text-[#173b3b]">Control anual</h3><p className="mt-1 text-sm leading-6 text-[#78918a]">Todo en orden. Peso saludable y energía excelente.</p></div><div><p className="text-xs font-bold text-[#d37c52]">03 Abr 2024</p><h3 className="mt-1 font-serif text-xl font-bold text-[#173b3b]">Vacuna séxtuple</h3><p className="mt-1 text-sm leading-6 text-[#78918a]">Próxima dosis recomendada en abril de 2025.</p></div></div></section> }
