'use client'

import { useMemo, useState } from 'react'
import { Banknote, Calculator, CircleDollarSign, LockKeyhole, Receipt, ShoppingCart } from 'lucide-react'
import { formatVES, rate, type Toast } from '@/lib/types'
import { CashCatalog, type CatalogItem } from './cash-catalog'
import { CustomerSelector } from './customer-selector'
import { SaleCart, type SaleItem } from './sale-cart'

export default function CashPage({ showToast }: { showToast: Toast }) {
  const [open, setOpen] = useState(false)
  const [opening, setOpening] = useState('100')
  const [customer, setCustomer] = useState('')
  const [payment, setPayment] = useState('Efectivo USD')
  const [items, setItems] = useState<SaleItem[]>([])
  const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.price * item.quantity, 0), [items])
  const add = (item: CatalogItem) => setItems((current) => { const found = current.find((line) => line.id === item.id); return found ? current.map((line) => line.id === item.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { ...item, quantity: 1 }] })
  const charge = () => { if (!items.length || !customer) return showToast('Selecciona un cliente y agrega al menos un artículo'); showToast(`Factura emitida por $${subtotal.toFixed(2)} · ${formatVES(subtotal)}`); setItems([]); setCustomer('') }
  if (!open) return <section className="mx-auto max-w-[1440px] px-6 py-8 lg:px-10"><Header open={open} setOpen={setOpen} showToast={showToast} /><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="rounded-[2rem] bg-[#e4efe8] p-7"><Calculator className="size-7 text-[#0d5c5b]" /><h2 className="mt-5 font-serif text-2xl font-bold text-[#173b3b]">Caja cerrada</h2><p className="mt-2 text-sm text-[#66817a]">Ingresa el fondo inicial para comenzar las ventas.</p><div className="mt-5 flex items-center gap-2 rounded-xl bg-white px-4 py-3"><span className="text-sm text-[#78918a]">$</span><input aria-label="Fondo inicial" value={opening} onChange={(e) => setOpening(e.target.value)} className="w-full bg-transparent text-sm font-bold outline-none" /></div></div><Summary icon={<CircleDollarSign />} label="Ventas de hoy" value="$0.00" /><Summary icon={<Receipt />} label="Facturas emitidas" value="0" /></div></section>
  return <section className="mx-auto max-w-[1440px] px-6 py-8 lg:px-10"><Header open={open} setOpen={setOpen} showToast={showToast} /><div className="mt-8 grid gap-6 xl:grid-cols-[1fr_420px]"><div className="flex flex-col gap-6"><CashCatalog onAdd={add} /><SaleCart items={items} onChange={setItems} /></div><aside className="flex flex-col gap-5"><CustomerSelector value={customer} onChange={setCustomer} /><div className="rounded-[2rem] bg-[#173b3b] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b8d8c8]">Resumen de factura</p><div className="mt-6 flex items-end justify-between"><span className="text-sm text-[#b8d8c8]">Total USD</span><strong className="font-serif text-4xl">${subtotal.toFixed(2)}</strong></div><div className="mt-2 flex items-center justify-between border-t border-white/15 pt-3"><span className="text-sm text-[#b8d8c8]">Total VES · tasa {rate}</span><strong>{formatVES(subtotal)}</strong></div><select aria-label="Método de pago" value={payment} onChange={(e) => setPayment(e.target.value)} className="mt-6 w-full rounded-xl bg-white/10 px-4 py-3 text-sm text-white outline-none"><option className="text-[#173b3b]">Efectivo USD</option><option className="text-[#173b3b]">Efectivo VES</option><option className="text-[#173b3b]">Tarjeta</option><option className="text-[#173b3b]">Pago móvil</option></select><button onClick={charge} className="mt-4 w-full rounded-xl bg-[#d37c52] px-4 py-3 text-sm font-bold text-white">Emitir factura</button></div></aside></div></section>
}
function Header({ open, setOpen, showToast }: { open: boolean; setOpen: (value: boolean) => void; showToast: Toast }) { return <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#d37c52]">Ventas</p><h1 className="mt-2 font-serif text-4xl font-bold text-[#173b3b]">Caja</h1><p className="mt-2 text-sm text-[#78918a]">Productos, servicios, clientes y facturación en un solo lugar.</p></div><button onClick={() => { setOpen(!open); if (open) showToast('Caja cerrada. Jornada conciliada') }} className="inline-flex items-center gap-2 rounded-xl bg-[#d37c52] px-4 py-3 text-sm font-bold text-white">{open ? <LockKeyhole className="size-4" /> : <Banknote className="size-4" />}{open ? 'Cerrar caja' : 'Abrir caja'}</button></header> }
function Summary({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-[2rem] bg-white p-7 ring-1 ring-[#e1ebe6]"><span className="text-[#0d5c5b]">{icon}</span><p className="mt-6 text-sm text-[#78918a]">{label}</p><b className="mt-1 block font-serif text-3xl text-[#173b3b]">{value}</b></div> }
